# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-16 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=100, unique=True, verbose_name='название актива')),
                ('asset_link', models.CharField(max_length=200, verbose_name='ссылка')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'актив',
                'verbose_name_plural': 'активы',
            },
        ),
        migrations.CreateModel(
            name='AssetsBeneficiaries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share', models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=6, verbose_name='доля бенефициара в активе, %')),
                ('rel_date', models.DateField(blank=True, null=True, verbose_name='дата актуальности')),
                ('source', models.CharField(blank=True, max_length=150, verbose_name='источник')),
                ('link', models.CharField(max_length=200, verbose_name='ссылка')),
                ('asset', models.ForeignKey(on_delete=models.SET(''), to='Offshores.Asset', verbose_name='актив')),
            ],
            options={
                'verbose_name': 'Бенефициар-Актив',
                'ordering': ['beneficiary__ben_lastname'],
                'verbose_name_plural': 'Бенефициры-Активы',
            },
        ),
        migrations.CreateModel(
            name='BeneficiariesOffshores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share', models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=7, verbose_name='доля бенефициара в офшоре, %')),
                ('rel_date', models.DateField(blank=True, null=True, verbose_name='дата актуальности')),
                ('source', models.CharField(blank=True, max_length=150, verbose_name='источник')),
                ('link', models.CharField(max_length=200, verbose_name='ссылка')),
            ],
            options={
                'verbose_name': 'Офшор-Бенефициар',
                'ordering': ['offshore'],
                'verbose_name_plural': 'Офшоры-Бенефициары',
            },
        ),
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ben_name', models.CharField(max_length=50, verbose_name='имя')),
                ('ben_lastname', models.CharField(max_length=100, verbose_name='фамилия')),
                ('ben_midname', models.CharField(blank=True, max_length=30, verbose_name='отчество')),
                ('ben_holding', models.CharField(blank=True, max_length=70, verbose_name='холдинговая компания бенефициара')),
                ('ben_link', models.CharField(max_length=200, verbose_name='ссылка')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'бенефициар',
                'verbose_name_plural': 'бенефициары',
                'ordering': ['ben_lastname', 'ben_name'],
            },
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=200, verbose_name='ссылка')),
                ('link_name', models.CharField(max_length=150, verbose_name='название ресурса')),
                ('link_login', models.CharField(max_length=50, verbose_name='логин для ресурса')),
                ('link_pass', models.CharField(max_length=50, verbose_name='пароль для ресурса')),
                ('link_dscr', models.TextField(verbose_name='примечания')),
            ],
            options={
                'verbose_name': 'Ресурс',
                'ordering': ['link_name'],
                'verbose_name_plural': 'Ресурсы',
            },
        ),
        migrations.CreateModel(
            name='Offshore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('off_name', models.CharField(max_length=50, unique=True, verbose_name='название офшора')),
                ('off_jurisdiction', models.CharField(blank=True, max_length=50, verbose_name='юрисдикция офшора')),
                ('file', models.FileField(blank=True, null=True, upload_to='offshores/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='offshores/')),
                ('off_parent', models.CharField(blank=True, max_length=50, verbose_name='материнский офшор')),
                ('off_link', models.CharField(max_length=200, verbose_name='ссылка')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'офшор',
                'ordering': ['off_name'],
                'verbose_name_plural': 'офшоры',
            },
        ),
        migrations.CreateModel(
            name='OffshoresAssets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share', models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=6, verbose_name='доля офшора в активе, %')),
                ('rel_date', models.DateField(blank=True, null=True, verbose_name='дата актуальности')),
                ('source', models.CharField(blank=True, max_length=150, verbose_name='источник')),
                ('link', models.CharField(max_length=200, verbose_name='ссылка')),
                ('asset', models.ForeignKey(on_delete=models.SET(''), to='Offshores.Asset', verbose_name='актив')),
                ('offshore', models.ForeignKey(on_delete=models.SET(''), to='Offshores.Offshore', verbose_name='офшор')),
            ],
            options={
                'verbose_name': 'Офшор-Актив',
                'ordering': ['offshore'],
                'verbose_name_plural': 'Офшоры-Активы',
            },
        ),
        migrations.AlterUniqueTogether(
            name='beneficiary',
            unique_together=set([('ben_name', 'ben_lastname', 'ben_midname')]),
        ),
        migrations.AddField(
            model_name='beneficiariesoffshores',
            name='beneficiary',
            field=models.ForeignKey(on_delete=models.SET(''), to='Offshores.Beneficiary', verbose_name='бенефициар'),
        ),
        migrations.AddField(
            model_name='beneficiariesoffshores',
            name='offshore',
            field=models.ForeignKey(on_delete=models.SET(''), to='Offshores.Offshore', verbose_name='офшор'),
        ),
        migrations.AddField(
            model_name='assetsbeneficiaries',
            name='beneficiary',
            field=models.ForeignKey(on_delete=models.SET(''), to='Offshores.Beneficiary', verbose_name='бенефициар'),
        ),
    ]
