# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-22 15:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=100, unique=True, verbose_name='название актива')),
            ],
            options={
                'verbose_name': 'актив',
                'verbose_name_plural': 'активы',
            },
        ),
        migrations.CreateModel(
            name='AssetsBeneficiaries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share', models.DecimalField(blank=True, decimal_places=4, max_digits=6, verbose_name='доля бенефициара в активе, %')),
                ('rel_date', models.DateField(blank=True, null=True, verbose_name='дата актуальности')),
                ('source', models.CharField(blank=True, max_length=150, verbose_name='источник')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Offshores.Asset', verbose_name='актив')),
            ],
            options={
                'verbose_name': 'Связь Активы-бенефициры',
                'verbose_name_plural': 'Связи Активы-бенефициры',
            },
        ),
        migrations.CreateModel(
            name='BeneficiariesOffshores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share', models.DecimalField(blank=True, decimal_places=4, max_digits=6, verbose_name='доля бенефициара в офшоре, %')),
                ('rel_date', models.DateField(blank=True, null=True, verbose_name='дата актуальности')),
                ('source', models.CharField(blank=True, max_length=150, verbose_name='источник')),
            ],
            options={
                'verbose_name': 'Связь Бенефициары-Офшоры',
                'verbose_name_plural': 'Связи Бенефициары-Офшоры',
            },
        ),
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ben_name', models.CharField(max_length=50, verbose_name='имя')),
                ('ben_lastname', models.CharField(max_length=100, verbose_name='фамилия')),
                ('ben_midname', models.CharField(blank=True, max_length=30, verbose_name='отчество')),
                ('ben_holding', models.CharField(blank=True, max_length=70, verbose_name='холдинговая компания бенефициара')),
            ],
            options={
                'ordering': ['ben_lastname', 'ben_name'],
                'verbose_name': 'бенефициар',
                'verbose_name_plural': 'бенефициары',
            },
        ),
        migrations.CreateModel(
            name='Offshore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('off_name', models.CharField(max_length=50, unique=True, verbose_name='название офшора')),
                ('off_jurisdiction', models.CharField(blank=True, max_length=50, verbose_name='юрисдикция офшора')),
                ('off_parent', models.CharField(blank=True, max_length=50, verbose_name='материнский офшор')),
            ],
            options={
                'verbose_name': 'офшор',
                'verbose_name_plural': 'офшоры',
            },
        ),
        migrations.CreateModel(
            name='OffshoresAssets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share', models.DecimalField(blank=True, decimal_places=4, max_digits=6, verbose_name='доля офшора в активе, %')),
                ('rel_date', models.DateField(blank=True, null=True, verbose_name='дата актуальности')),
                ('source', models.CharField(blank=True, max_length=150, verbose_name='источник')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Offshores.Asset', verbose_name='актив')),
                ('offshore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Offshores.Offshore', verbose_name='офшор')),
            ],
            options={
                'verbose_name': 'Связь Офшоры-Активы',
                'verbose_name_plural': 'Связи Офшоры-Активы',
            },
        ),
        migrations.AlterUniqueTogether(
            name='beneficiary',
            unique_together=set([('ben_name', 'ben_lastname', 'ben_midname')]),
        ),
        migrations.AddField(
            model_name='beneficiariesoffshores',
            name='beneficiary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Offshores.Beneficiary', verbose_name='бенефициар'),
        ),
        migrations.AddField(
            model_name='beneficiariesoffshores',
            name='offshore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Offshores.Offshore', verbose_name='офшор'),
        ),
        migrations.AddField(
            model_name='assetsbeneficiaries',
            name='beneficiary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Offshores.Beneficiary', verbose_name='бенефициар'),
        ),
    ]
