# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-22 16:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Offshores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offshoresassets',
            options={'verbose_name': 'Связь Активы-Офшоры', 'verbose_name_plural': 'Связи Активы-Офшоры'},
        ),
    ]
