# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-16 19:44
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Offshores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_link',
            field=models.CharField(blank=True, max_length=200, verbose_name='ссылка'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='asset',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='assetsbeneficiaries',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='assetsbeneficiaries',
            name='link',
            field=models.CharField(blank=True, max_length=200, verbose_name='ссылка'),
        ),
        migrations.AlterField(
            model_name='beneficiariesoffshores',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='beneficiariesoffshores',
            name='link',
            field=models.CharField(blank=True, max_length=200, verbose_name='ссылка'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='ben_link',
            field=models.CharField(blank=True, max_length=200, verbose_name='ссылка'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='links',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='offshore',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='offshore',
            name='off_link',
            field=models.URLField(blank=True, max_length=300, verbose_name='ссылка'),
        ),
        migrations.AlterField(
            model_name='offshore',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='offshoresassets',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='offshoresassets',
            name='link',
            field=models.CharField(blank=True, max_length=200, verbose_name='ссылка'),
        ),
    ]
