# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-23 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Offshores', '0002_auto_20160722_1906'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetsbeneficiaries',
            options={'verbose_name': 'Актив-бенефициар', 'verbose_name_plural': 'Активы-бенефициры'},
        ),
        migrations.AlterModelOptions(
            name='beneficiariesoffshores',
            options={'verbose_name': 'Бенефициар-Офшор', 'verbose_name_plural': 'Бенефициары-Офшоры'},
        ),
        migrations.AlterModelOptions(
            name='offshoresassets',
            options={'verbose_name': 'Актив-Офшор', 'verbose_name_plural': 'Активы-Офшоры'},
        ),
        migrations.AlterField(
            model_name='beneficiariesoffshores',
            name='share',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=6, verbose_name='доля бенефициара в офшоре, %'),
        ),
    ]
