# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-23 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Offshores', '0003_auto_20160723_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetsbeneficiaries',
            name='share',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=6, verbose_name='доля бенефициара в активе, %'),
        ),
        migrations.AlterField(
            model_name='offshoresassets',
            name='share',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=6, verbose_name='доля офшора в активе, %'),
        ),
    ]
