# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-23 15:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Offshores', '0006_auto_20160723_1846'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetsbeneficiaries',
            options={'verbose_name': 'Актив-Бенефициар', 'verbose_name_plural': 'Активы-Бенефициры'},
        ),
    ]
