# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-24 10:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Offshores', '0008_auto_20160724_1320'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetsbeneficiaries',
            options={'verbose_name': 'Бенефициар-Актив', 'verbose_name_plural': 'Бенефициры-Активы'},
        ),
    ]
