# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-31 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Offshores', '0009_auto_20160724_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='offshore',
            name='image',
            field=models.ImageField(blank=True, upload_to='/media/offshores/'),
        ),
    ]
