# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-03 15:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Offshores', '0011_auto_20160803_1732'),
        ('Offshores', '0011_auto_20160803_1611'),
    ]

    operations = [
    ]
