# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-03 18:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Offshores', '0017_auto_20160803_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetsbeneficiaries',
            name='rel_date',
        ),
        migrations.RemoveField(
            model_name='beneficiariesoffshores',
            name='rel_date',
        ),
        migrations.RemoveField(
            model_name='offshoresassets',
            name='rel_date',
        ),
    ]
