# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Offshores', '0018_auto_20160803_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetsbeneficiaries',
            name='rel_date',
            field=models.TextField(blank=True, null=True, verbose_name='дата актуальности'),
        ),
        migrations.AddField(
            model_name='beneficiariesoffshores',
            name='rel_date',
            field=models.DateField(blank=True, null=True, verbose_name='дата актуальности'),
        ),
        migrations.AddField(
            model_name='offshoresassets',
            name='rel_date',
            field=models.DateField(blank=True, null=True, verbose_name='дата актуальности'),
        ),
    ]
